development:
  password: f8b5bec204f197cc40f9e0d8bcbaafa5
  theme_id: "live"
  store: shitshitshitshitshitshit.myshopify.com
production:
  password: f8b5bec204f197cc40f9e0d8bcbaafa5
  theme_id: 'live'
  store: shitshitshitshitshitshit.myshopify.com
  timeout: 30s
